name: Bug Report
description: Report a bug or other issue

title: "[Bug]: "

labels:
    - bug
    - common

assignees:
    - andrey-helldar

body:
    -   type: input
        id: environment-package-name
        attributes:
            label: Lang Package Name
            description: The name of the package in which the bug was found.
            placeholder: laravel-lang/common
        validations:
            required: true

    -   type: input
        id: environment-package-version
        attributes:
            label: Lang Package Version
            description: The version of the package in which the bug was found.
            placeholder: 1.2.3
        validations:
            required: true

    -   type: input
        id: environment-laravel
        attributes:
            label: Laravel Framework Version
            description: The version of the Laravel framework in which you encountered the problem.
            placeholder: 10.30.0
        validations:
            required: true

    -   type: input
        id: environment-php
        attributes:
            label: PHP Version
            placeholder: 8.2.12
        validations:
            required: true

    -   type: textarea
        id: dependencies
        attributes:
            label: Dependencies
            description: |
                Provide the `require` and `require-dev` sections content from the `composer.json` file if you can.
        validations:
            required: false

    -   type: textarea
        id: description
        attributes:
            label: Issue description
            description: |
                Be as specific and detailed as possible to help us triaging your issue. Screenshots and/or animations can be very useful in helping to understand the issue you're facing.

                Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
                Tip: You can use https://www.screentogif.com to record animations and videos.
        validations:
            required: true

    -   type: textarea
        id: steps
        attributes:
            label: Steps to reproduce
            description: Take some time to try and reproduce the issue, then explain how to do so here.
        validations:
            required: true

    -   type: markdown
        attributes:
            value: |
                ❤️ Laravel Lang? Please consider supporting our collective on [Boosty](https://boosty.to/laravel-lang).
