name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
    Update:
        uses: Laravel-Lang/.github/.github/workflows/release-drafter.yml@main
